spring.application.name=userDetails
spring.datasource.url = jdbc:mysql://localhost:3306/user details?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=pavan
spring.jpa.hibernate.ddl-auto=update
server.port=9090

